apiVersion: v1
kind: Namespace
metadata:
  name: safe-services-ns
  labels:
    istio-injection: enabled
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: safe-deployment-v1
  namespace: safe-services-ns
spec:
  selector:
    matchLabels:
      app: httpbin
  template:
    metadata:
      labels:
        app: httpbin
        version: "1"
    spec:
      containers:
        - name: httpbin
          image: kennethreitz/httpbin
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 200m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - name: http-httpbin
              containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: httpbin-service
  namespace: safe-services-ns
spec:
  selector:
    app: httpbin
  ports:
    - name: http-httpbin-service
      port: 80
      targetPort: http-httpbin
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpbin-vservice
  namespace: safe-services-ns
spec:
  hosts:
    - "*"
  gateways:
    - httpbin-gw
  http:
    - route:
        - destination:
            host: httpbin-service
            port:
              number: 80
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: httpbin-gw
  namespace: safe-services-ns
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http-httpbin-gw
        protocol: HTTP
      hosts:
        - "*"
